### PR TITLE
Matomo Tracking plugin

### PR DESCRIPTION
**Pull request by mliradelc**
Here is my first draft for a Matomo Tracking plugin, still work in progress

### CODE REVIEW

**Comment by mliradelc** [comment]
Ok, I started to work more on this, and still webpack is very difficult, now I have "context" issues and I don't know what to do.  

@ferserc1 I'm t[rying to load the Matomo JS](https://github.com/polimediaupv/paella-user-tracking/blob/94a9259d28bdcfcc5834b64b994a7edf0a716ad8/src/plugins/org.opencast.analytics.matomoUserTrackingDataPlugin.js) with the snipped you gave me, but the plugin does not get loaded because the "context" is not found. 

What I'm missing?

**Comment by ferserc1** [comment]
I have published an (extensive, very extensive) tutorial on how to create your own plugin library, from creating the base project to publishing it to npm. You can check it out on the [paella player website](https://paellaplayer.upv.es/#/doc/plugin_module_tutorial.md) or directly in the paella-core documentation folder.

The tutorial also has a corresponding code repository: [https://github.com/polimediaupv/plugin-module-tutorial](https://github.com/polimediaupv/plugin-module-tutorial)

**Comment by mliradelc** [comment]
😃 !! That is a new document that I haven't seen before.  I will look into that

**Comment by ferserc1** [comment]
it's normal that you didn't see it before, because I just added it this morning XD

**Comment by mliradelc** [comment]
Closing in favor of https://github.com/polimediaupv/opencast/pull/34

**Pull request closed without merging**
