### PR TITLE
Matomo plugin

### PR DESCRIPTION
**Pull request by mliradelc**
Hi

This is the Matomo plugin, as discussed, is the same version from Opencast https://github.com/opencast/opencast/pull/3754 

I hope that you can find why it won't run on the standalone version.

Cheers

Max

### CODE REVIEW

**Comment by mliradelc** [comment]
Hi guys, can you please take a look at my plugin problem?, we want to move to paella 7 the next semester that will start in 2 months. Still I don't know why can't be executed in standalone Paella.

**Comment by miesgre** [comment]
Hi @mliradelc, paella-user-tracking@1.5.0 has matomo support. You can test it. Next week, I will make an updated plugin for opencast.

**Comment by miesgre** [comment]
@mliradelc You can test the matomo plugin for opencast in this branch: https://github.com/miesgre/opencast/tree/paella7-matomo

Please test it and if it works for you I will make a PR

**Comment by mliradelc** [comment]
Hi Miguel, thanks for your answer. I was sick last week, but today I will check it out.

If all goes correct, I can continue developing the plugin to add the cookie banner like in the 6.x version.

**Comment by mliradelc** [comment]
I just made some tests, works very well, but there something that I'm checking about, I hope to get the results early.

**Comment by mliradelc** [comment]
I will make a new post on Issues to talk about the new code, I will close this PR because the code is not the same as the one in the repo

**Pull request closed without merging**
